env: "local" # "local" #dev, prod

sqlite_path: "./storage/sqlite.db"

postgres:
  host: "localhost"
  port: 5432
  user: "wnd"
  password: "123"
  dbname: "wnd"
  sslmode: "disable"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  workflow_status: 1 # 1 - workflow (tests) status / 0 - launch status

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s

