env: "local" #dev, prod

sqlite_path: "./internal/storage/sqlite.db"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "---"
  dbname: "---"
  sslmode: "disable"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

